[paths]
directory = "access_seed42"
results = "access_seed42/results"
outputs = "access_seed42/outputs"
script = "access_seed42/access_script.py"
setup = "access_seed42/access_setup.toml"
epochs = "access_seed42/epochs_pop50.csv"
epochs_scaled = "access_seed42/epochs_pop50_scaled.csv"
history = "access_seed42/history_pop50.csv"
history_scaled = "access_seed42/history_pop50_scaled.csv"

[setup]
scaling = [ 0.32000000000000006, 0.6400000000000001, 0.6400000000000001, 0.32000000000000006, 0.32000000000000006, 0.4, 0.4, 0.4, 0.4, 144.0, 0.4, 144.0, 0.4, 144.0, 144.0, 144.0, 200.0, 6.4, 3.2, 1.6, 72.0, 3.2, 2.0,]
population = 50
target = 0.1
seed = 42

[setup.parameters.value]
bottom_clearance = 0.3
xplace = 0.0
yplace = 0.0
"impeller/height_ratio" = 0.092857
"impeller/diameter_ratio" = 0.335
"impeller/0/place_rel" = 0.597
"impeller/0/xlen_rel" = 0.806
"impeller/0/ylen_rel" = 0.003
"impeller/0/joint_place" = 0.5
"impeller/0/joint_angle" = 0.0
"impeller/0/lean_place" = 0.5
"impeller/0/lean_angle" = 0.0
"impeller/0/turn_place" = 0.5
"impeller/0/turn_angle" = 0.0
"impeller/0/twist" = 0.0
"impeller/0/helix" = 0.0
"impeller/0/curl" = 0.0
"impeller/0/around_number" = 6.0
"impeller/0/repeat_number" = 1.0
"impeller/0/repeat_heights_equal" = 2.0
"impeller/0/repeat_angles_bias" = 90.0
"impeller/fidgetsurface/0/alpha1" = 0.0
"impeller/fidgetsurface/0/beta1" = 0.01

[setup.parameters.min]
bottom_clearance = 0.0
xplace = -0.8
yplace = -0.8
"impeller/height_ratio" = 0.0
"impeller/diameter_ratio" = 0.0
"impeller/0/place_rel" = 0.0
"impeller/0/xlen_rel" = 0.0
"impeller/0/ylen_rel" = 0.0
"impeller/0/joint_place" = 0.0
"impeller/0/joint_angle" = -180.0
"impeller/0/lean_place" = 0.0
"impeller/0/lean_angle" = -180.0
"impeller/0/turn_place" = 0.0
"impeller/0/turn_angle" = -180.0
"impeller/0/twist" = 0.0
"impeller/0/helix" = 0.0
"impeller/0/curl" = 0.0
"impeller/0/around_number" = 0.5
"impeller/0/repeat_number" = 0.5
"impeller/0/repeat_heights_equal" = 0.0
"impeller/0/repeat_angles_bias" = 0.0
"impeller/fidgetsurface/0/alpha1" = 0.0
"impeller/fidgetsurface/0/beta1" = 0.0

[setup.parameters.max]
bottom_clearance = 0.8
xplace = 0.8
yplace = 0.8
"impeller/height_ratio" = 0.8
"impeller/diameter_ratio" = 0.8
"impeller/0/place_rel" = 1.0
"impeller/0/xlen_rel" = 1.0
"impeller/0/ylen_rel" = 1.0
"impeller/0/joint_place" = 1.0
"impeller/0/joint_angle" = 180.0
"impeller/0/lean_place" = 1.0
"impeller/0/lean_angle" = 180.0
"impeller/0/turn_place" = 1.0
"impeller/0/turn_angle" = 180.0
"impeller/0/twist" = 360.0
"impeller/0/helix" = 360.0
"impeller/0/curl" = 500.0
"impeller/0/around_number" = 16.5
"impeller/0/repeat_number" = 8.5
"impeller/0/repeat_heights_equal" = 4.0
"impeller/0/repeat_angles_bias" = 180.0
"impeller/fidgetsurface/0/alpha1" = 8.0
"impeller/fidgetsurface/0/beta1" = 5.0

[setup.parameters.sigma]
bottom_clearance = 0.32000000000000006
xplace = 0.6400000000000001
yplace = 0.6400000000000001
"impeller/height_ratio" = 0.32000000000000006
"impeller/diameter_ratio" = 0.32000000000000006
"impeller/0/place_rel" = 0.4
"impeller/0/xlen_rel" = 0.4
"impeller/0/ylen_rel" = 0.4
"impeller/0/joint_place" = 0.4
"impeller/0/joint_angle" = 144.0
"impeller/0/lean_place" = 0.4
"impeller/0/lean_angle" = 144.0
"impeller/0/turn_place" = 0.4
"impeller/0/turn_angle" = 144.0
"impeller/0/twist" = 144.0
"impeller/0/helix" = 144.0
"impeller/0/curl" = 200.0
"impeller/0/around_number" = 6.4
"impeller/0/repeat_number" = 3.2
"impeller/0/repeat_heights_equal" = 1.6
"impeller/0/repeat_angles_bias" = 72.0
"impeller/fidgetsurface/0/alpha1" = 3.2
"impeller/fidgetsurface/0/beta1" = 2.0

[setup.parameters_scaled.value]
bottom_clearance = 0.9374999999999998
xplace = 0.0
yplace = 0.0
"impeller/height_ratio" = 0.29017812499999995
"impeller/diameter_ratio" = 1.0468749999999998
"impeller/0/place_rel" = 1.4925
"impeller/0/xlen_rel" = 2.015
"impeller/0/ylen_rel" = 0.0075
"impeller/0/joint_place" = 1.25
"impeller/0/joint_angle" = 0.0
"impeller/0/lean_place" = 1.25
"impeller/0/lean_angle" = 0.0
"impeller/0/turn_place" = 1.25
"impeller/0/turn_angle" = 0.0
"impeller/0/twist" = 0.0
"impeller/0/helix" = 0.0
"impeller/0/curl" = 0.0
"impeller/0/around_number" = 0.9375
"impeller/0/repeat_number" = 0.3125
"impeller/0/repeat_heights_equal" = 1.25
"impeller/0/repeat_angles_bias" = 1.25
"impeller/fidgetsurface/0/alpha1" = 0.0
"impeller/fidgetsurface/0/beta1" = 0.005

[setup.parameters_scaled.min]
bottom_clearance = 0.0
xplace = -1.2499999999999998
yplace = -1.2499999999999998
"impeller/height_ratio" = 0.0
"impeller/diameter_ratio" = 0.0
"impeller/0/place_rel" = 0.0
"impeller/0/xlen_rel" = 0.0
"impeller/0/ylen_rel" = 0.0
"impeller/0/joint_place" = 0.0
"impeller/0/joint_angle" = -1.25
"impeller/0/lean_place" = 0.0
"impeller/0/lean_angle" = -1.25
"impeller/0/turn_place" = 0.0
"impeller/0/turn_angle" = -1.25
"impeller/0/twist" = 0.0
"impeller/0/helix" = 0.0
"impeller/0/curl" = 0.0
"impeller/0/around_number" = 0.078125
"impeller/0/repeat_number" = 0.15625
"impeller/0/repeat_heights_equal" = 0.0
"impeller/0/repeat_angles_bias" = 0.0
"impeller/fidgetsurface/0/alpha1" = 0.0
"impeller/fidgetsurface/0/beta1" = 0.0

[setup.parameters_scaled.max]
bottom_clearance = 2.4999999999999996
xplace = 1.2499999999999998
yplace = 1.2499999999999998
"impeller/height_ratio" = 2.4999999999999996
"impeller/diameter_ratio" = 2.4999999999999996
"impeller/0/place_rel" = 2.5
"impeller/0/xlen_rel" = 2.5
"impeller/0/ylen_rel" = 2.5
"impeller/0/joint_place" = 2.5
"impeller/0/joint_angle" = 1.25
"impeller/0/lean_place" = 2.5
"impeller/0/lean_angle" = 1.25
"impeller/0/turn_place" = 2.5
"impeller/0/turn_angle" = 1.25
"impeller/0/twist" = 2.5
"impeller/0/helix" = 2.5
"impeller/0/curl" = 2.5
"impeller/0/around_number" = 2.578125
"impeller/0/repeat_number" = 2.65625
"impeller/0/repeat_heights_equal" = 2.5
"impeller/0/repeat_angles_bias" = 2.5
"impeller/fidgetsurface/0/alpha1" = 2.5
"impeller/fidgetsurface/0/beta1" = 2.5

[setup.parameters_scaled.sigma]
bottom_clearance = 1.0
xplace = 1.0
yplace = 1.0
"impeller/height_ratio" = 1.0
"impeller/diameter_ratio" = 1.0
"impeller/0/place_rel" = 1.0
"impeller/0/xlen_rel" = 1.0
"impeller/0/ylen_rel" = 1.0
"impeller/0/joint_place" = 1.0
"impeller/0/joint_angle" = 1.0
"impeller/0/lean_place" = 1.0
"impeller/0/lean_angle" = 1.0
"impeller/0/turn_place" = 1.0
"impeller/0/turn_angle" = 1.0
"impeller/0/twist" = 1.0
"impeller/0/helix" = 1.0
"impeller/0/curl" = 1.0
"impeller/0/around_number" = 1.0
"impeller/0/repeat_number" = 1.0
"impeller/0/repeat_heights_equal" = 1.0
"impeller/0/repeat_angles_bias" = 1.0
"impeller/fidgetsurface/0/alpha1" = 1.0
"impeller/fidgetsurface/0/beta1" = 1.0
